apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-mysql
  name: flask-mysql
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: "TCP"
  selector:
    app: flask-mysql
